ENH: modify wrapping to produce float mesh coordinate type
When used with unsigned char input images, which is the common case,
the produced mesh would use UC as coordinate type.
This would not only cause a massive loss in precision and range,
but is not wrapped with itk::Mesh class thus causing runtime error:

   itk.meshwrite(mesh, file_path)
     ...
itk.support.extras.TemplateTypeError: itk.MeshFileWriter is not wrapped for input type `itk.Mesh[itk.UC,3]`.
To limit the size of the package, only a limited number of
types are available in ITK Python.
...
Supported input types:
itk.Mesh[itk.F,2]
itk.Mesh[itk.D,2]
itk.Mesh[itk.F,3]
itk.Mesh[itk.D,3]